version: "3.8"

services:
    db:
        image: "mysql:8.1"
        environment:
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASS
            MYSQL_ROOT_PASSWORD: $DB_PASS
            MYSQL_DATABASE: $DB_NAME
        ports:
            - "${DB_PORT:-13306}:3306"
        volumes:
            - ./docker/mysql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
        networks:
            testprove:

    redis:
        image: redis:7.2
        ports:
            - "${REDIS_PORT:-6379}:6379"

networks:
    testprove:
        name: testprove
